### ISSUE TITLE
Deal with redis disconnects

### ISSUE THREAD

**Issue by madfordmac** [madfordmac/netban#2]
Right now, if the redis server goes down for, say, a software update, the code is too dumb to try reconnecting.

**Comment by madfordmac** [comment]
Here's the traceback from a redis restart:
```
Task exception was never retrieved                                                                                                                                                                          
future: <Task finished coro=<NetBanLocalFile.processExpiry() done, defined at /home/alex/Developer/netban/netban/local/__init__.py:57> exception=ConnectionError('Connection closed by server.')>           
Traceback (most recent call last):                                                                                                                                                                          
  File "/home/alex/Developer/netban/netban/local/__init__.py", line 66, in processExpiry
    message = await chan.get_message(ignore_subscribe_messages=True)
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/asyncio/client.py", line 1032, in get_message                                                                                   
    response = await self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/asyncio/client.py", line 910, in parse_response                                                                                 
    push_request=True,
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/asyncio/client.py", line 887, in _execute                                                                                       
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/asyncio/retry.py", line 62, in call_with_retry                                                                                  
    await fail(error)
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/asyncio/client.py", line 874, in _disconnect_raise_connect                                                                      
    raise error
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry                                                                                  
    return await do()
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/asyncio/connection.py", line 503, in read_response                                                                              
    disable_decoding=disable_decoding
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/_parsers/hiredis.py", line 203, in read_response                                                                                
    await self.read_from_socket()
  File "/home/alex/Developer/netban/venv/lib/python3.7/site-packages/redis/_parsers/hiredis.py", line 186, in read_from_socket                                                                             
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR) from None
redis.exceptions.ConnectionError: Connection closed by server.
```
